app = "redis-stack"
primary_region = "nrt"

[mounts]
  destination = "/data"
  source = "redis_server"

[metrics]
  port = 9091
  path = "/metrics"

# https://fly.io/docs/reference/configuration/
[build.args]
  REDIS_VERSION = "7.2.0-v15"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1


# https://fly.io/docs/reference/configuration/#the-checks-section

# [[services]]
#   internal_port = 6379
#   protocol = "tcp"

#   [services.concurrency]
#     hard_limit = 200
#     soft_limit = 190
#     type = "connections"

#   [[services.ports]]
#     handlers = []
#     port = "10000"

#   [[services.tcp_checks]]
#     interval = 10000
#     timeout  = 2000

